@startuml inline_umlgraph_1.svg
title Calculation of pixel's new coordinate
start
floating note left
  X and Y are pixel's current
  coordinates in 2D space
end note
floating note right
  I'M SO SORRY FOR CREATING YOU, MY SON
  GOD FORBID ME FOR MY SINS
end note
if ([X, Y - 1]) then (can move)
  :[X, Y - 1];
else (can't move)
  switch (PixelType)
  case (SAND)
    if ([X - 1, Y - 1] & [X - 1, Y] &
[X + 1, Y - 1] & [X + 1, Y]) then (can move)
      :rand([X - 1, Y]
or [X + 1, Y]);

    else (can't move)
    if ([X - 1, Y - 1]
& [X - 1, Y]) then (can move)
      :[X - 1, Y];

    else (can't move)
    if ([X + 1, Y - 1]
& [X + 1, Y]) then (can move)
      :[X + 1, Y];

    else (can't move)
      :[X, Y];
    endif
    endif
    endif

  case (WATER)
    if ([X - 1, Y - 1] &
[X + 1, Y - 1]) then (can move)
      :rand([X - 1, Y - 1]
or [X + 1, Y - 1]);

    else (can't move)
    if ([X - 1, Y - 1]) then (can move)
      :[X - 1, Y - 1];

    else (can't move)
    if ([X + 1, Y - 1]) then (can move)
      :[X + 1, Y - 1];

    else (can't move)
      if ([X - 1, Y] &
[X + 1, Y]) then (can move)
        :rand([X - 1, Y]
or [X + 1, Y]);
 
      else (can't move)
      if ([X - 1, Y] then (can move)
        :[X - 1, Y];
 
      else (can't move)
      if ([X + 1, Y] then (can move)
        :[X + 1, Y];
 
      else (can't move)
        :[X, Y];
      endif
      endif
      endif
    endif
    endif
    endif
  endswitch
@enduml
@startuml inline_umlgraph_2.svg
title Function flow
if (window was resized?) then (yes)
  :Update World::window_size and
World::texture to match actual
        window size;
else (no)
endif
:Call recalcWorld();
if (mouse_is_down) then (true)
  :Call addPixel();
else (false)
endif
:Redraw pixels on World::texture and render;
:Text render;
@enduml
